<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="1" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="40070" started-at="2019-06-27T14:27:20Z" finished-at="2019-06-27T14:28:00Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="40070" started-at="2019-06-27T14:27:20Z" finished-at="2019-06-27T14:28:00Z">
      <class name="com.edgeconnect.test.mobiletest.LoginTest">
        <test-method status="PASS" signature="setUpReport()[pri:0, instance:com.edgeconnect.test.mobiletest.LoginTest@318ba8c8]" name="setUpReport" is-config="true" duration-ms="215" started-at="2019-06-27T14:27:20Z" finished-at="2019-06-27T14:27:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpReport -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.edgeconnect.test.mobiletest.LoginTest@318ba8c8]" name="beforeMethod" is-config="true" duration-ms="25987" started-at="2019-06-27T14:27:20Z" finished-at="2019-06-27T14:27:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.edgeconnect.test.mobiletest.LoginTest.verifyInvaldUserNameLogin()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="verifyInvaldUserNameLogin()[pri:2, instance:com.edgeconnect.test.mobiletest.LoginTest@318ba8c8]" name="verifyInvaldUserNameLogin" duration-ms="10443" started-at="2019-06-27T14:27:46Z" description="Verify Login with invalid username" finished-at="2019-06-27T14:27:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Validating the error for invalid id expected [Please enter valid username/email/password1] but found [Please enter valid username/email/password]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Validating the error for invalid id expected [Please enter valid username/email/password1] but found [Please enter valid username/email/password]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at com.edgeconnect.test.mobiletest.LoginTest.verifyInvaldUserNameLogin(LoginTest.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyInvaldUserNameLogin -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.edgeconnect.test.mobiletest.LoginTest@318ba8c8]" name="tearDown" is-config="true" duration-ms="3201" started-at="2019-06-27T14:27:57Z" finished-at="2019-06-27T14:28:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyInvaldUserNameLogin status=FAILURE method=LoginTest.verifyInvaldUserNameLogin()[pri:2, instance:com.edgeconnect.test.mobiletest.LoginTest@318ba8c8] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:com.edgeconnect.test.mobiletest.LoginTest@318ba8c8]" name="afterSuite" is-config="true" duration-ms="0" started-at="2019-06-27T14:28:00Z" finished-at="2019-06-27T14:28:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.edgeconnect.test.mobiletest.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
